---
- name: Add postgres repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- include: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- name: Ensure packages are installed
  apt: name={{item}}
  with_items:
    - postgresql-9.4
    - libpq-dev
    - python-psycopg2